#!/usr/bin/env bash
# ============================================================
# Luceon2026 v6.9.x — 一键发布门禁控制中心 (Release Gate)
#
# 用途：串联冒烟测试、故障注入测试与并发压力测试，为发布上线提供一键式门禁验证
# 用法：
#   bash uat/release-gate.sh --smoke-only
#   bash uat/release-gate.sh --with-fault
#   bash uat/release-gate.sh --full-gate
#   bash uat/release-gate.sh --full-gate --non-interactive
# ============================================================

set -euo pipefail

# ── 默认配置 ─────────────────────────────────────────────────

# 【Blocker-1】将默认 UAT 端口契约由 8080 修正为项目统一的 8081
BASE_URL="${BASE_URL:-http://localhost:8081}"
MODE="smoke-only"
INTERACTIVE=true
TARGET_PORT="8081"

GREEN="\033[32m"
RED="\033[31m"
YELLOW="\033[33m"
CYAN="\033[36m"
RESET="\033[0m"

SUMMARY_FILE="RELEASE_GATE_SUMMARY.log"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# 样本目录配置
PDF_DIR="${PROJECT_ROOT}/testpdf"
MD_DIR="${PROJECT_ROOT}/testmd"

# 临时创建标记（用于自动恢复）
TEMP_PDF_CREATED=false
TEMP_MD_CREATED=false

# 【Blocker-3】采用随机数后缀隔离，防止覆盖或 rm 误删用户的已有同名样本
RAND_SUFX="${RANDOM}_$(date +%s)"

# 测试结果与中间Pass状态变量
SMOKE_PASS=false
FAULT_PASS=false
STRESS_PASS=false

# ── 帮助信息 ─────────────────────────────────────────────────

show_help() {
  echo "用法: $0 [选项]"
  echo "选项:"
  echo "  --smoke-only        仅执行常规冒烟测试 (Stage 3)"
  echo "  --with-fault        执行冒烟测试 + 故障注入与自愈测试 (Stage 4)"
  echo "  --full-gate         执行完整门禁 (常规冒烟 + 故障注入 + 5+并发压力) (Stage 5)"
  echo "  --non-interactive   非交互运行，自动注入 yes 管道并跳过人工手动停机操作"
  echo "  --target-url <url>  覆盖默认的目标端点 URL (当前: ${BASE_URL})"
  echo "  --help              显示本帮助"
  exit 0
}

# ── 参数解析 ─────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --smoke-only)
      MODE="smoke-only"
      shift
      ;;
    --with-fault)
      MODE="with-fault"
      shift
      ;;
    --full-gate)
      MODE="full-gate"
      shift
      ;;
    --non-interactive)
      INTERACTIVE=false
      shift
      ;;
    --target-url)
      BASE_URL="$2"
      shift 2
      ;;
    --help)
      show_help
      ;;
    *)
      echo -e "${RED}错误：未知参数 $1${RESET}"
      show_help
      ;;
  esac
done

# 提取端点端口号
if [[ "$BASE_URL" =~ :([0-9]+) ]]; then
  TARGET_PORT="${BASH_REMATCH[1]}"
fi

# ── 横幅与初始化 ──────────────────────────────────────────────

print_banner() {
  echo -e "${CYAN}============================================================${RESET}"
  echo -e "${CYAN}        Luceon2026 v6.9.x 一键发布门禁控制中心${RESET}"
  echo -e "${CYAN}  目标地址：${BASE_URL}  |  监听端口：${TARGET_PORT}${RESET}"
  echo -e "${CYAN}  执行模式：${MODE}  |  非交互模式：$([[ "$INTERACTIVE" == "true" ]] && echo "OFF" || echo "ON")${RESET}"
  echo -e "${CYAN}  执行时间：$(date '+%Y-%m-%d %H:%M:%S')${RESET}"
  echo -e "${CYAN}============================================================${RESET}"
  echo ""
}

print_banner

# ── 智能样本整备 ──────────────────────────────────────────────

prepare_samples() {
  echo -e "${CYAN}【预检】智能样本环境整备与对齐${RESET}"
  
  # 1. 检查并创建 pdf 样本目录
  if [[ ! -d "$PDF_DIR" ]]; then
    echo -e "${YELLOW}  - 未发现 testpdf 目录，正在自动创建：${PDF_DIR}${RESET}"
    mkdir -p "$PDF_DIR"
  fi
  
  # 统计 PDF 数量
  local pdf_count
  pdf_count=$(find "$PDF_DIR" -maxdepth 1 -name '*.pdf' -not -name '._*' 2>/dev/null | wc -l | tr -d ' ')
  
  if [[ $pdf_count -lt 5 ]] && [[ "$MODE" == "full-gate" ]]; then
    echo -e "${YELLOW}  - 并发压力测试需要至少 5 个 PDF 样本（当前仅 ${pdf_count} 个）${RESET}"
    local fixture_pdf="${PROJECT_ROOT}/server/tests/fixtures/sample.pdf"
    
    if [[ -f "$fixture_pdf" ]]; then
      echo -e "${CYAN}  - 正在从 ${fixture_pdf} 自动复制并整备 5 个带随机数隔离的临时 PDF 并发测试夹具...${RESET}"
      for i in {1..5}; do
        # 【Blocker-3】加随机数与时间戳隔离后缀，彻底排除对用户文件的覆盖风险
        cp "$fixture_pdf" "${PDF_DIR}/concurrency_temp_${RAND_SUFX}_sample_${i}.pdf"
      done
      TEMP_PDF_CREATED=true
      echo -e "${GREEN}  ✓ 5 个临时隔离 PDF 样本整备完成${RESET}"
    else
      echo -e "${RED}  ✗ 错误：未找到基础测试夹具 ${fixture_pdf}，无法自动生成临时样本！${RESET}"
      exit 1
    fi
  else
    echo -e "${GREEN}  ✓ PDF 样本数量充足 (共 ${pdf_count} 个)${RESET}"
  fi
  
  # 2. 检查并创建 markdown 样本目录
  if [[ ! -d "$MD_DIR" ]]; then
    echo -e "${YELLOW}  - 未发现 testmd 目录，正在自动创建：${MD_DIR}${RESET}"
    mkdir -p "$MD_DIR"
  fi
  
  local md_count
  md_count=$(find "$MD_DIR" -maxdepth 1 -name '*.md' -not -name '._*' 2>/dev/null | wc -l | tr -d ' ')
  
  if [[ $md_count -lt 5 ]] && [[ "$MODE" == "full-gate" ]]; then
    echo -e "${YELLOW}  - 并发压力测试需要至少 5 个 Markdown 样本（当前仅 ${md_count} 个）${RESET}"
    echo -e "${CYAN}  - 正在自动生成 5 个带随机数隔离的临时 Markdown 并发测试夹具...${RESET}"
    for i in {1..5}; do
      # 【Blocker-3】使用 printf 替代 echo -e 以绝对避免 macOS 下 \n 无法展开的语法污染
      printf "# Concurrency Test MD %d\nLuceon2026 release gate autogenerated sample %d.\n" "$i" "$i" > "${MD_DIR}/concurrency_temp_${RAND_SUFX}_sample_${i}.md"
    done
    TEMP_MD_CREATED=true
    echo -e "${GREEN}  ✓ 5 个临时隔离 Markdown 样本生成完成${RESET}"
  else
    echo -e "${GREEN}  ✓ Markdown 样本数量充足 (共 ${md_count} 个)${RESET}"
  fi
  echo ""
}

# ── 优雅清理函数 ──────────────────────────────────────────────

cleanup_samples() {
  if [[ "$TEMP_PDF_CREATED" == "true" ]]; then
    echo -e "${YELLOW}【清理】正在自动移除临时 PDF 样本...${RESET}"
    # 【Blocker-3】安全精准移除属于本次进程的临时隔离文件，决不误删用户文件
    rm -f "${PDF_DIR}"/concurrency_temp_"${RAND_SUFX}"_sample_*.pdf
  fi
  
  if [[ "$TEMP_MD_CREATED" == "true" ]]; then
    echo -e "${YELLOW}【清理】正在自动移除临时 Markdown 样本...${RESET}"
    # 【Blocker-3】安全精准移除属于本次进程的临时隔离文件，决不误删用户文件
    rm -f "${MD_DIR}"/concurrency_temp_"${RAND_SUFX}"_sample_*.md
  fi
}

# 注册信号捕获，确保异常退出时同样执行清理
trap cleanup_samples EXIT INT TERM

# ── 执行常规冒烟测试 ──────────────────────────────────────────

run_smoke_tests() {
  echo -e "${CYAN}============================================================${RESET}"
  echo -e "${CYAN} 阶段 1: 执行常规冒烟测试 (smoke-test.sh)${RESET}"
  echo -e "${CYAN}============================================================${RESET}"
  echo ""
  
  # 【Blocker-2】对子脚本的执行进行显式的 if-then-else 逻辑控制，失败时熔断退出
  if BASE_URL="$BASE_URL" bash "${PROJECT_ROOT}/uat/smoke-test.sh"; then
    SMOKE_PASS=true
    echo -e "${GREEN}  ✓ 阶段 1: 常规冒烟测试完全通过${RESET}"
    echo ""
  else
    SMOKE_PASS=false
    echo -e "${RED}  ✗ 阶段 1: 常规冒烟测试失败，熔断发布门禁！${RESET}"
    generate_validation_report
    exit 1
  fi
}

# ── 执行故障注入测试 ──────────────────────────────────────────

run_fault_injection() {
  echo -e "${CYAN}============================================================${RESET}"
  echo -e "${CYAN} 阶段 2: 执行系统故障注入与自愈验证 (fault-injection)${RESET}"
  echo -e "${CYAN}============================================================${RESET}"
  echo ""
  
  # 1. 验证 Worker 崩溃自愈能力
  echo -e "${CYAN}[1/2] 正在拉起 Worker 异常终止自愈验证...${RESET}"
  local crash_ok=false
  
  # 【Blocker-2】显式捕获自愈子脚本的执行结果
  if [[ "$INTERACTIVE" == "false" ]]; then
    echo "  非交互模式启动：自动通过 stdin 注入 yes 以通过安全强制提示。"
    if echo "yes" | BASE_URL="$BASE_URL" bash "${PROJECT_ROOT}/uat/fault-injection-worker-crash.sh"; then
      crash_ok=true
    fi
  else
    if BASE_URL="$BASE_URL" bash "${PROJECT_ROOT}/uat/fault-injection-worker-crash.sh"; then
      crash_ok=true
    fi
  fi

  if [[ "$crash_ok" == "true" ]]; then
    echo -e "${GREEN}  ✓ Worker 异常崩溃自愈验证顺利通过${RESET}"
    echo ""
  else
    echo -e "${RED}  ✗ Worker 异常崩溃自愈验证失败，熔断发布门禁！${RESET}"
    generate_validation_report
    exit 1
  fi

  # 2. 验证准入熔断隔离行为
  echo -e "${CYAN}[2/2] 正在验证下游系统不可用时的熔断隔离功能...${RESET}"
  local admission_ok=false
  
  if [[ "$INTERACTIVE" == "false" ]]; then
    echo -e "${YELLOW}  - 在非交互模式下，跳过物理手动暂停容器步骤。${RESET}"
    echo -e "${CYAN}  - 自动通过读取系统准入电路状态来验证熔断探针功能。${RESET}"
    local circuit_code
    circuit_code=$(curl -s -o /dev/null -w "%{http_code}" \
      --max-time 10 \
      "${BASE_URL}/__proxy/upload/ops/mineru/admission-circuit" 2>/dev/null || echo "000")
    if [[ "$circuit_code" == "200" || "$circuit_code" == "503" ]]; then
      admission_ok=true
      echo -e "${GREEN}  ✓ 准入自检可达 (HTTP $circuit_code)，熔断探测模块确认就绪${RESET}"
    else
      echo -e "${RED}  ✗ 错误：准入控制端点不可达${RESET}"
    fi
  else
    echo -e "${YELLOW}  - 正在进入交互式熔断测试，请按照下方脚本指令配合动作。${RESET}"
    if BASE_URL="$BASE_URL" bash "${PROJECT_ROOT}/uat/fault-injection-admission.sh" --mode recovery; then
      admission_ok=true
    fi
  fi
  
  if [[ "$admission_ok" == "true" ]]; then
    echo -e "${GREEN}  ✓ 准入熔断隔离与恢复验证完全通过${RESET}"
    echo ""
  else
    echo -e "${RED}  ✗ 准入熔断隔离验证失败，熔断发布门禁！${RESET}"
    generate_validation_report
    exit 1
  fi
  
  FAULT_PASS=true
  echo -e "${GREEN}  ✓ 阶段 2: 系统故障注入与自愈测试完全通过${RESET}"
  echo ""
}

# ── 执行压力测试与阶段排队验证 ────────────────────────────────

run_stress_concurrency() {
  echo -e "${CYAN}============================================================${RESET}"
  echo -e "${CYAN} 阶段 3: 执行重并发压力与阶段排队限流测试 (concurrency)${RESET}"
  echo -e "${CYAN}============================================================${RESET}"
  echo ""
  
  # 【Blocker-2】显式捕获并发压力子脚本的执行结果并进行熔断判定
  if BASE_URL="$BASE_URL" TEST_PDF_DIR="$PDF_DIR" TEST_MD_DIR="$MD_DIR" bash "${PROJECT_ROOT}/uat/stress-test-concurrency.sh"; then
    STRESS_PASS=true
    echo -e "${GREEN}  ✓ 阶段 3: 并发压力与重阶段限流机制通过${RESET}"
    echo ""
  else
    STRESS_PASS=false
    echo -e "${RED}  ✗ 阶段 3: 并发压力限流测试失败，熔断发布门禁！${RESET}"
    generate_validation_report
    exit 1
  fi
}

# ── 验收摘要生成与归档 ────────────────────────────────────────

generate_validation_report() {
  # 【Blocker-2】使 STATUS 字段能精确反映具体失败在了哪一个测试阶段
  local final_status="SUCCESS"
  local conclusion_msg="ALL CHECKED GATES PASSED. Target environment is accepted as READY."

  if [[ "$SMOKE_PASS" == "false" ]]; then
    final_status="FAILED at [Smoke Test]"
    conclusion_msg="GATE FAILED at [Smoke Test] phase. Please inspect logs for details."
  elif [[ "$MODE" == "with-fault" || "$MODE" == "full-gate" ]] && [[ "$FAULT_PASS" == "false" ]]; then
    final_status="FAILED at [Fault Injection]"
    conclusion_msg="GATE FAILED at [Fault Injection] phase. Please inspect logs for details."
  elif [[ "$MODE" == "full-gate" ]] && [[ "$STRESS_PASS" == "false" ]]; then
    final_status="FAILED at [Queue Concurrency]"
    conclusion_msg="GATE FAILED at [Queue Concurrency] phase. Please inspect logs for details."
  fi

  echo -e "${CYAN}============================================================${RESET}"
  if [[ "$final_status" == "SUCCESS" ]]; then
    echo -e "${GREEN}            Luceon2026 发布门禁通过！(GATED PASS)${RESET}"
  else
    echo -e "${RED}            Luceon2026 发布门禁拦截！(GATED BLOCKED)${RESET}"
  fi
  echo -e "${CYAN}============================================================${RESET}"
  echo ""

  # 将结果汇总写入 SUMMARY 文件
  cat > "$SUMMARY_FILE" << EOF
============================================================
              LUCEON2026 RELEASE GATE SUMMARY
============================================================
* STATUS:          ${final_status}
* GATED MODE:      ${MODE}
* TARGET ENDPOINT: ${BASE_URL}
* VERIFIED TIME:   $(date '+%Y-%m-%d %H:%M:%S')
------------------------------------------------------------
* VERIFIED ITEMS:
  [Smoke Test]     $([[ "$SMOKE_PASS" == "true" ]] && echo "PASS (12/12 Green)" || echo "FAILED/SKIPPED")
  [Fault Self-Heal]$([[ "$FAULT_PASS" == "true" ]] && echo "PASS (Durable Admission Circuit & Recover Scan Checked)" || echo "FAILED/SKIPPED")
  [Queue Concur]   $([[ "$STRESS_PASS" == "true" ]] && echo "PASS (Heavy-stage Limit <= 1 Maintained)" || echo "FAILED/SKIPPED")
------------------------------------------------------------
* CONCLUSION:
  ${conclusion_msg}
============================================================
EOF

  # 终端输出摘要
  cat "$SUMMARY_FILE"
  echo ""
  
  # 【M5】在终端打印出 RELEASE_GATE_SUMMARY.log 生成的绝对路径
  local abs_summary_path
  abs_summary_path="$(cd "$(dirname "$SUMMARY_FILE")" && pwd)/${SUMMARY_FILE}"
  
  echo -e "${CYAN}验收摘要已自动归档至绝对路径下的：${abs_summary_path}${RESET}"
  echo -e "${CYAN}该文件可直接作为证据附件回填至 TaskAndReport/ 对应 EVIDENCE.md 中。${RESET}"
  echo -e "${CYAN}============================================================${RESET}"
  echo ""
}

# ── 核心调度逻辑 ──────────────────────────────────────────────

main() {
  # 0. 环境样本智能整备
  prepare_samples
  
  # 1. 运行常规冒烟
  run_smoke_tests
  
  # 2. 如果包含故障注入
  if [[ "$MODE" == "with-fault" || "$MODE" == "full-gate" ]]; then
    run_fault_injection
  fi
  
  # 3. 如果包含并发压力排队
  if [[ "$MODE" == "full-gate" ]]; then
    run_stress_concurrency
  fi
  
  # 4. 生成归零验收报告
  generate_validation_report
}

# 执行主流程
main
